version: "3"

services:

  backend:
    restart: always
    build: ./task-manager
    ports:
      - 3000:3000
    environment:
      APP_NAME: youtube_api
      MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - express-mongo
  mongo:

    restart: always
    image: mongo:7.0.5

    volumes:
      - mongodb_data:/data/db

    networks:
      - express-mongo
    ports:
      - 27017:27017
    expose:
      - 27017
volumes:
  mongodb_data:

networks:
  react-express:
  express-mongo:


  
