version: "3"

services:
  backend:
    build: ./task-manager
    ports:
      - 3000:3000
    environment:
      APP_NAME: data_apis
      PORT: 3000
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:7.0.5
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

  
